sudo: required

language: c

addons:
  apt:
    packages:
    - graphviz
    - python-pip

branches:
  except:
    - gh-pages

after_success:
  - echo "** BUILDING AND DEPLOYING DOC TO GH-PAGES **"
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user sphinx sphinx_rtd_theme sphinxcontrib-bibtex
  - openssl aes-256-cbc -K $encrypted_2c91c605ab0a_key -iv $encrypted_2c91c605ab0a_iv -in stravis.key.enc -out ~/.ssh/stravis.key -d
  - eval "$(ssh-agent -s)"
  - chmod 0600 ~/.ssh/stravis.key
  - ssh-add ~/.ssh/stravis.key
  - echo "** Build and deploy DOC **"
  - make doc
  - make doc-publish
