language: c

addons:
  apt:
    packages:
    - graphviz
    - python-pip
    - cmake

branches:
  except:
    - gh-pages

before_install:
  - echo "** BUILDING AND DEPLOYING DOC TO GH-PAGES **"
  - export PATH=$HOME/.local/bin:$PATH
  - echo "** Installing sphinx-doc **"
  - pip install --user sphinx sphinx_rtd_theme sphinxcontrib-bibtex
  - openssl aes-256-cbc -K $encrypted_2c91c605ab0a_key -iv $encrypted_2c91c605ab0a_iv -in ci/stravis.key.enc -out ~/.ssh/stravis.key -d
  - eval "$(ssh-agent -s)"
  - chmod 0600 ~/.ssh/stravis.key
  - ssh-add ~/.ssh/stravis.key
  - make doc
  - make doc-publish

install:
  - echo "** Install **"

before_script:
  - echo "** Before script **"

script:
  - echo "** Script **"

after_success:
  - echo "** After success **"
